package App;


/**
* App/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Tuesday, 25 July 2017 09:44:58 o'clock GMT+05:30
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  String client1 (String a);
  String client2 (String b);
  String client1Data ();
  String client2Data ();
  void shutdown ();
} // interface AdditionOperations
