package App;

/**
* App/AdditionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Tuesday, 25 July 2017 09:44:58 o'clock GMT+05:30
*/

public final class AdditionHolder implements org.omg.CORBA.portable.Streamable
{
  public App.Addition value = null;

  public AdditionHolder ()
  {
  }

  public AdditionHolder (App.Addition initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.AdditionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.AdditionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.AdditionHelper.type ();
  }

}
