package App;


/**
* App/AdditionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Tuesday, 25 July 2017 09:44:58 o'clock GMT+05:30
*/

public abstract class AdditionPOA extends org.omg.PortableServer.Servant
 implements App.AdditionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("client1", new java.lang.Integer (1));
    _methods.put ("client2", new java.lang.Integer (2));
    _methods.put ("client1Data", new java.lang.Integer (3));
    _methods.put ("client2Data", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // App/Addition/add
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.add (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // App/Addition/client1
       {
         String a = in.read_string ();
         String $result = null;
         $result = this.client1 (a);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // App/Addition/client2
       {
         String b = in.read_string ();
         String $result = null;
         $result = this.client2 (b);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // App/Addition/client1Data
       {
         String $result = null;
         $result = this.client1Data ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // App/Addition/client2Data
       {
         String $result = null;
         $result = this.client2Data ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // App/Addition/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:App/Addition:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Addition _this() 
  {
    return AdditionHelper.narrow(
    super._this_object());
  }

  public Addition _this(org.omg.CORBA.ORB orb) 
  {
    return AdditionHelper.narrow(
    super._this_object(orb));
  }


} // class AdditionPOA
